"""add_slug_and_editorial_fields

Revision ID: aa30b544ed16
Revises: 78c2862565de
Create Date: 2026-07-30 23:48:31.169876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa30b544ed16'
down_revision: Union[str, Sequence[str], None] = '78c2862565de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editorial_scores', sa.Column('features', sa.JSON(), nullable=True))
    op.add_column('editorial_scores', sa.Column('recommended_for', sa.JSON(), nullable=True))
    op.add_column('editorial_scores', sa.Column('editors_choice', sa.Boolean(), nullable=True))
    op.add_column('editorial_scores', sa.Column('override_rank', sa.Integer(), nullable=True))
    op.add_column('motorcycles', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_motorcycles_slug'), 'motorcycles', ['slug'], unique=False)
    op.add_column('products', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_column('products', 'slug')
    op.drop_index(op.f('ix_motorcycles_slug'), table_name='motorcycles')
    op.drop_column('motorcycles', 'slug')
    op.drop_column('editorial_scores', 'override_rank')
    op.drop_column('editorial_scores', 'editors_choice')
    op.drop_column('editorial_scores', 'recommended_for')
    op.drop_column('editorial_scores', 'features')
    # ### end Alembic commands ###
